/**
 * Created by ravikant on 22/6/14.
 */
module.exports={
		"Telugu":{"___name___":"Telugu"},
		"English":{"___name___":"English"},
		"Bengali":{"___name___":"Bengali"},
		"Bodo":{"___name___":"Bodo"},
		"Urdu":{"___name___":"Urdu"},
		"Hindi":{"___name___":"Hindi"},
		"Konkani":{"___name___":"Konkani"},
		"Gujarati":{"___name___":"Gujarati"},
		"Punjabi":{"___name___":"Punjabi"},
		"Santali":{"___name___":"Santali"},
		"Kannada":{"___name___":"Kannada"},
		"Malayalam":{"___name___":"Malayalam"}, 
		"Marathi":{"___name___":"Marathi"},
		"Manipuri":{"___name___":"Manipuri"},
		"Khasi":{"___name___":"Khasi"},
		"Garo":{"___name___":"Garo"},
		"Mizo":{"___name___":"Mizo"},
		"Oriya":{"___name___":"Oriya"},
		"Nepali":{"___name___":"Nepali"},
		"Tamil":{"___name___":"Tamil"},
		"Kokborok":{"___name___":"Kokborok"},
		"Sanskrit":{"___name___":"Sanskrit"}
}
